import '@/styles/globals.scss';
import Context  from '@/component/Context';
import Layout from '@/component/Layout';
import Head from 'next/head';
import Link from 'next/link';




export default function App({ Component, pageProps }) {


  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app; charSet=UTF-8" />
        <meta charset="UTF-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <Link href='/'>home</Link>
      <Link href='/profile'>profile</Link>
      <Link href='/work'>work</Link>
      <Context>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Context>
    </>
  )
}
